### ISSUE TITLE
App\Http\Controllers\Admin\AdminController::create does not exist.

### ISSUE THREAD

**Issue by dlgatdio** [atefdiabmohamed/laravelpos#50]
App\Http\Controllers\Admin\AdminController::create does not exist.

**Comment by atefdiabmohamed** [comment]
in this file 
https://github.com/atefdiabmohamed/laravelpos/blob/master/app/Http/Controllers/Admin/LoginController.php
there is function called  make_new_admin run it in tinker to create first user or import the full database 
https://github.com/atefdiabmohamed/laravelpos/blob/master/laravel9_sales.sql
As for the multiplicity of adding users, it will be in the future in the Permissions item

**Comment by dlgatdio** [comment]
thanks alot
have a nice day
جزاك الله كل الخير
